display:
  cycle: true
  inverted: false
  orientation: 90
  trendingmode: false
  showvolume: false
  showrank: false
  24h: true
ticker:
  currency: bitcoin,ethereum,cardano
  exchange: default
  fiatcurrency: usd,eur,gbp
  sparklinedays: 1 
  updatefrequency: 300

